#!/bin/bash
if [ ! -z $1 ] && [ ! -z $2 ] && [ ! -z $3 ]; then
  for file in $3
  do
    CUR_SHEBANG="#!$1"
    NEW_SHEBANG="#!$2"
    if (file "${file}" |grep 'ASCII text executable$' >/dev/null 2>&1); then
      sed -i "s|$CUR_SHEBANG|$NEW_SHEBANG|" $file
    fi
  done
fi
